export { DATABASE_NAME, DATABASE_VERSION, runMigrations } from './migrations';
export {
  saveGenres,
  saveSongCatalog,
  saveStarCounts,
  saveTierData,
  upsertGenre,
  upsertSong,
  upsertChart,
  linkGenreSong,
  type SongCatalogItem,
} from './songs';
export {
  saveRecords,
  insertRecordIfChanged,
  buildRecordQuery,
  getDiffsInRange,
  getScoreUpdateDays,
  rowToRecord,
  resolveTargetsByTitle,
  parseOptionList,
  type RecordFilter,
  type RecordSort,
  type RecordSortKey,
  type RecordListRow,
  type TodayDiffRow,
  type ScoreUpdateDay,
} from './records';
export { listPlayers, addPlayer, removePlayer } from './players';
export {
  getMeta,
  setMeta,
  getAlmostConfig,
  getMainLevels,
  SELF_TAIKO_NO_KEY,
  ALMOST_MODE_KEY,
  ALMOST_VALUE_KEY,
  MAIN_LEVELS_KEY,
  type AlmostMode,
  type AlmostConfig,
} from './meta';
export {
  listManualFolders,
  createFolder,
  renameFolder,
  deleteFolder,
  addSongToFolder,
  removeSongFromFolder,
  getFoldersForSong,
  getFolderSongs,
  getFolderSongNumbers,
  getFolderSongDetails,
  getSmartFolderRecords,
  searchCatalogSongs,
  type FolderRef,
  type FolderSongRow,
  type ManualFolderRow,
  type FolderSongDetail,
  type CatalogSongRow,
} from './folders';
export { exportDatabase, importDatabase } from './backup';
