/**
 * src/scrape/inject.entry.ts を IIFE バンドルし、WebView 注入用の文字列として
 * src/scrape/inject-script.ts を生成する。
 *
 *   bun run build:inject
 */
import { $ } from 'bun';

const ENTRY = './src/scrape/inject.entry.ts';
const TMP = './node_modules/.cache/done-inject.js';
const OUT = './src/scrape/inject-script.ts';

await $`bun build --target browser --format iife --minify --outfile ${TMP} ${ENTRY}`;

const js = await Bun.file(TMP).text();
await Bun.write(
  OUT,
  `// Auto-generated by scripts/build-inject.ts — do not edit manually\n` +
    `export const INJECT_SCRIPT = ${JSON.stringify(js)};\n`,
);

console.log(`Generated ${OUT} (${js.length} bytes of injected JS)`);
